services:
  postgres:
    image: postgres:16-alpine
    container_name: tauriflix-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxxxxxxxxxxx # removi a senha git baitola
      POSTGRES_DB: tauriflix
    ports:
      - "5432:5432"
    volumes:
      - tauriflix_pgdata:/var/lib/postgresql/data

volumes:
  tauriflix_pgdata:
